music/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # /music/
    path(r'^$', views.index, name='index'),

    # /music/712/
    path(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as user_views

urlpatterns = [
    path(r'^admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)


class Song(models.Model):
       album = models.ForeignKey(Album, on_delete=models.CASCADE)
       file_type = models.CharField(max_length=10)
       song_title = models.CharField(max_length=250)

users/models.py
from django.db import models

# Create your models here.

music/views.py
from django.http import HttpResponse
from .models import Album

def index(request):
    all_albums = Album.objects.all()
    html = ''
    for album in all_albums:
       path = '/music/' + str(album.id) + '/'
    return HttpResponse(html)

def detail(request, album_id):
    return HttpResponse("<h2>Details for Album id: " + str(album_id) + "</h2>")

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

def register(request):
    form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}

<img src="{{album.album_logo}}" style="width: 250px;">

<h1>{{album.album_title}}</h1>
<h2>{{album.artist}}</h2>

   {% for song in album.song_set.all %}
{{song.song_title}}
{% if song.is_favorite %}
<img src="https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.facebook.com%2Fpages%2Fcategory%2FMuseum%2FBeautiful-natural-pictures-114689571912941%2F&psig=AOvVaw1ckLHHVUxW48X9oiCUT1i6&ust=1599058378665000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNjU5OeayOsCFQAAAAAdAAAAABAD"/>
{% endif %}
<br>
{% endfor %}
{% endblock %}











<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

music/templates/music/index.html
<nav class ="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topnavbar">
<span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url '
            music:index' %}">Raihan</a>
        </div>
    </div>
</nav>


{% if all_albums %}
<h3> Here are all my Albums:</h3>
<ul>
    {% for album in all_albums %}
    <li> <a href="{% url 'music:detail'album.id %}">{{album.album_title}}</a>
    </li>
    { % endfor % }
</ul>
  { % else % }
<h3> you don't have any albums</h3>
{ % endif % }

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

users/templates/users/register.html
{% extends "admin/base.html" %}
{% block content %}

<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Raihan's blog</legend>
            {{ form.as_p }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="#">Sign In</a>
        </small>
    </div>
</div>
{% endblock content %}